version: '3.2'
services:
  
  crawler:
    build: .
    volumes:
      - ./:/var/www/html:rw
    env_file: .env
    ports:
      - "80:80"
    environment:
      TZ: America/Sao_Paulo
      LANG: pt_BR.UTF-8
      LANGUAGE: pt_BR.UTF-8
      LC_CTYPE: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8
      LC_TIME: pt_BR.UTF-8

volumes:
  data:
